In [1]:
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
from matplotlib.colors import LinearSegmentedColormap
import folium
from shapely.wkt import loads
import numpy as np

In [2]:
df = pd.read_csv('../../data/processed/land_dataset_final_v3.csv')

In [3]:
df.shape

(9272, 234)

In [4]:
df.dropna(inplace=True)

In [5]:
df

,address_subdivision,address_locality,address_line_2,h_id,price_per_m2,land_area,price,longitude,latitude,near_Koh_Pich_in_km,...,f_road,f_secondary,f_service,f_steps,f_tertiary,f_track,f_trunk,f_trunk_link,f_unclassified,f_unused
0,Phnom Penh,Mean Chey,Stueng Mean Chey,8865846a91fffff,3357.98,52,174614.96,104.883100,11.552932,6,...,0,1,1,0,0,0,0,0,0,0
1,Phnom Penh,Chamkar Mon,Phsar Daeum Thkov,8865846acbfffff,3809.30,178,678055.40,104.915003,11.528833,3,...,0,0,0,0,0,0,0,0,0,0
2,Phnom Penh,Saensokh,Phnom Penh Thmei,88658468cbfffff,3437.03,138,474310.14,104.886163,11.586713,7,...,0,0,1,0,0,0,0,0,0,0
3,Phnom Penh,Saensokh,Phnom Penh Thmei,8865846ab1fffff,3469.70,162,562091.40,104.889529,11.575790,6,...,0,0,0,0,0,0,0,0,0,0
4,Phnom Penh,Doun Penh,Chakto Mukh,8865846a39fffff,5442.34,200,1088468.00,104.958218,11.558388,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9267,Phnom Penh,Chraoy Chongvar,Bak Kaeng,886586a699fffff,729.57,182,132781.74,104.929226,11.701893,16,...,0,0,0,0,0,0,0,0,0,0
9268,Phnom Penh,Chraoy Chongvar,Preaek Ta Sek,8865846995fffff,571.98,212,121259.76,104.899855,11.667508,13,...,0,0,0,0,0,0,0,0,0,0
9269,Phnom Penh,Praek Pnov,Ponsang,8865846d85fffff,260.40,134,34893.60,104.756877,11.633307,22,...,0,0,0,0,0,0,0,0,0,0
9270,Phnom Penh,Pur SenChey,Kantaok,8865846e31fffff,1093.83,230,251580.90,104.785133,11.523526,17,...,0,0,1,0,0,0,0,0,0,0
9271,Phnom Penh,Praek Pnov,Samraong,886580d00bfffff,201.59,150,30238.50,104.818512,11.719658,23,...,0,0,0,0,0,0,0,0,0,0

In [6]:
df

,address_subdivision,address_locality,address_line_2,h_id,price_per_m2,land_area,price,longitude,latitude,near_Koh_Pich_in_km,...,f_road,f_secondary,f_service,f_steps,f_tertiary,f_track,f_trunk,f_trunk_link,f_unclassified,f_unused
0,Phnom Penh,Mean Chey,Stueng Mean Chey,8865846a91fffff,3357.98,52,174614.96,104.883100,11.552932,6,...,0,1,1,0,0,0,0,0,0,0
1,Phnom Penh,Chamkar Mon,Phsar Daeum Thkov,8865846acbfffff,3809.30,178,678055.40,104.915003,11.528833,3,...,0,0,0,0,0,0,0,0,0,0
2,Phnom Penh,Saensokh,Phnom Penh Thmei,88658468cbfffff,3437.03,138,474310.14,104.886163,11.586713,7,...,0,0,1,0,0,0,0,0,0,0
3,Phnom Penh,Saensokh,Phnom Penh Thmei,8865846ab1fffff,3469.70,162,562091.40,104.889529,11.575790,6,...,0,0,0,0,0,0,0,0,0,0
4,Phnom Penh,Doun Penh,Chakto Mukh,8865846a39fffff,5442.34,200,1088468.00,104.958218,11.558388,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9267,Phnom Penh,Chraoy Chongvar,Bak Kaeng,886586a699fffff,729.57,182,132781.74,104.929226,11.701893,16,...,0,0,0,0,0,0,0,0,0,0
9268,Phnom Penh,Chraoy Chongvar,Preaek Ta Sek,8865846995fffff,571.98,212,121259.76,104.899855,11.667508,13,...,0,0,0,0,0,0,0,0,0,0
9269,Phnom Penh,Praek Pnov,Ponsang,8865846d85fffff,260.40,134,34893.60,104.756877,11.633307,22,...,0,0,0,0,0,0,0,0,0,0
9270,Phnom Penh,Pur SenChey,Kantaok,8865846e31fffff,1093.83,230,251580.90,104.785133,11.523526,17,...,0,0,1,0,0,0,0,0,0,0
9271,Phnom Penh,Praek Pnov,Samraong,886580d00bfffff,201.59,150,30238.50,104.818512,11.719658,23,...,0,0,0,0,0,0,0,0,0,0

In [7]:
import folium
from folium.plugins import MarkerCluster

# Center map on Phnom Penh (or your area of interest)
m = folium.Map(location=[df['latitude'].mean(), df['longitude'].mean()], zoom_start=12)

# Normalize price_per_m2 for color scaling
import matplotlib
norm = matplotlib.colors.Normalize(vmin=df['price_per_m2'].min(), vmax=df['price_per_m2'].max())
cmap = matplotlib.cm.get_cmap('viridis')

# Add points to map
for _, row in df.iterrows():
    color = matplotlib.colors.rgb2hex(cmap(norm(row['price_per_m2'])))
    folium.CircleMarker(
        location=[row['latitude'], row['longitude']],
        radius=4,
        color=color,
        fill=True,
        fill_color=color,
        fill_opacity=0.7,
        popup=f"Price/m²: {row['price_per_m2']:.2f}"
    ).add_to(m)

m.save('realestate_price_map.html')

C:\Users\User\AppData\Local\Temp\ipykernel_21016\1498732564.py:10: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = matplotlib.cm.get_cmap('viridis')

In [8]:
df['id'] = range(1, len(df) + 1)

In [9]:
import plotly.express as px

fig = px.scatter_mapbox(
    df,
    lat="latitude",
    lon="longitude",
    color="price_per_m2",
    hover_data=["price_per_m2"],
    zoom=12,
    height=600
)
fig.update_layout(mapbox_style="open-street-map")

# Enable click events in Jupyter
fig.show()

# You can then use Plotly's click events (with Dash or JupyterDash) to remove points from your DataFrame.

C:\Users\User\AppData\Local\Temp\ipykernel_21016\1151482528.py:3: DeprecationWarning: *scatter_mapbox* is deprecated! Use *scatter_map* instead. Learn more at: https://plotly.com/python/mapbox-to-maplibre/
  fig = px.scatter_mapbox(