In [1]:
from math import radians, cos, sin, asin, sqrt
import pandas as pd

In [2]:
# from geopy.geocoders import Nominatim
# import pandas as pd
# import time

# # Your place keywords
# places = [
#     "AEON Mall 1 Phnom Penh",
#     "AEON Mall 2 Phnom Penh",
#     "AEON Mall 3 Phnom Penh",
#     "Diamond Island Phnom Penh",
#     "Royal Palace Phnom Penh",
#     "Sisowath Quay Phnom Penh",
#     "Vattanac Capital Tower Phnom Penh",
#     "Bassac Lane Phnom Penh",
#     "Russian Market Phnom Penh",
#     "ISPP International School Phnom Penh",
#     "Northbridge International School Phnom Penh",
#     "Camko City Phnom Penh",
#     "Chroy Changvar Bridge Phnom Penh",
#     "Olympic Stadium Phnom Penh",
#     "Central Market Phnom Penh"
# ]

# geolocator = Nominatim(user_agent="phnompenh-geo-scraper")
# results = []

# for place in places:
#     try:
#         location = geolocator.geocode(place + ", Phnom Penh, Cambodia")
#         if location:
#             results.append({
#                 "name": place,
#                 "lat": location.latitude,
#                 "lon": location.longitude
#             })
#             print(f"✔ Found: {place} -> ({location.latitude}, {location.longitude})")
#         else:
#             results.append({"name": place, "lat": None, "lon": None})
#             print(f"✖ Not Found: {place}")
#     except Exception as e:
#         print(f"⚠️ Error for {place}: {e}")
#         results.append({"name": place, "lat": None, "lon": None})
#     time.sleep(1)  # Be polite to API (rate limiting)

In [3]:
# places= pd.DataFrame(results)

In [4]:
# Haversine distance function
def haversine(lat1, lon1, lat2, lon2):
    R = 6371  # Radius of Earth in km
    dlat = radians(lat2 - lat1)
    dlon = radians(lon2 - lon1)
    a = sin(dlat / 2)**2 + cos(radians(lat1)) * cos(radians(lat2)) * sin(dlon / 2)**2
    return R * 2 * asin(sqrt(a))

In [5]:
places = [
    {"name": "Koh_Pich", "lat": 11.551377, "lon": 104.941998},
    {"name": "Russian_Market", "lat": 11.541022, "lon": 104.914067},
    {"name": "AEON_Mall_1", "lat": 11.5479772, "lon": 104.9323125},
    {"name": "AEON_Mall_2", "lat": 11.5987765, "lon": 104.8825985},
    {"name": "AEON_Mall_3", "lat": 11.4841593, "lon": 104.91524},
    {"name": "Bassac_Lane", "lat": 11.5529714, "lon": 104.9271472},
    {"name": "Koh_Norea", "lat": 11.5441525, "lon": 104.9529025},
    {"name": "Camko_City", "lat": 11.5940666, "lon": 104.8912984},
    {"name": "Olympic_Stadium", "lat": 11.5596514, "lon": 104.90982},
    {"name": "Phsar_Tmey", "lat": 11.569552, "lon": 104.9183331},
    {"name": "Boeng_Keng_Kang_1", "lat": 11.551141, "lon": 104.9228331},
    {"name": "Wat_Phnom", "lat": 11.5759527, "lon": 104.9211453},
    {"name": "Chroy_Changvar_Bridge", "lat": 11.5872047, "lon": 104.9191252},
    {"name": "Vattanac_Tower", "lat": 11.5729518, "lon": 104.9170059},
    {"name": "Royal_Palace", "lat": 11.5638469, "lon": 104.9283975},
    {"name": "Sisowath_Riverside_Park", "lat": 11.5694802, "lon": 104.9316061},
    {"name": "Phnom_Penh_Airport", "lat": 11.5497995, "lon": 104.8375804},
    {"name": "Phsar_Chas", "lat": 11.5732803, "lon": 104.9257973},
    {"name": "Phsar_kandal", "lat": 11.5686593, "lon": 104.9288564}
]

In [6]:
df = pd.read_csv("../../../data/processed/realestate_clean_name_ppl.csv")

In [7]:
df

,price,land_area,address_line_2,latitude,longitude,price_per_m2,geometry,index_right,population,h_id
0,1100000.0,124.0,Chakto Mukh,11.575610,104.920250,8870.967742,POINT (104.92025 11.57561),53920.0,16252.0,8865846aadfffff
1,1100000.0,124.0,Chakto Mukh,11.575610,104.920250,8870.967742,POINT (104.92025 11.57561),53920.0,16252.0,8865846aadfffff
2,1100000.0,124.0,Chakto Mukh,11.575610,104.920250,8870.967742,POINT (104.92025 11.57561),53920.0,16252.0,8865846aadfffff
3,1100000.0,124.0,Chakto Mukh,11.575610,104.920250,8870.967742,POINT (104.92025 11.57561),53920.0,16252.0,8865846aadfffff
4,1100000.0,124.0,Chakto Mukh,11.575610,104.920250,8870.967742,POINT (104.92025 11.57561),53920.0,16252.0,8865846aadfffff
...,...,...,...,...,...,...,...,...,...,...
7160,550000.0,550000.0,Boeng Reang,11.575837,104.920096,1.000000,POINT (104.920096 11.575837),53920.0,16252.0,8865846aadfffff
7161,550000.0,550000.0,Boeng Reang,11.575837,104.920096,1.000000,POINT (104.920096 11.575837),53920.0,16252.0,8865846aadfffff
7162,550000.0,550000.0,Boeng Reang,11.575837,104.920096,1.000000,POINT (104.920096 11.575837),53920.0,16252.0,8865846aadfffff
7163,550000.0,550000.0,Boeng Reang,11.575837,104.920096,1.000000,POINT (104.920096 11.575837),53920.0,16252.0,8865846aadfffff
7164,550000.0,550000.0,Boeng Reang,11.575837,104.920096,1.000000,POINT (104.920096 11.575837),53920.0,16252.0,8865846aadfffff

In [8]:
# Loop over places and add distance-band columns
for place in places:
    name = place["name"]
    
    def encode_range(row):
        d = haversine(row['latitude'], row['longitude'], place['lat'], place['lon'])
        return {
            f"near_{name}_in_km": int(d),
            f"{name}_nearest": int(d <= 1),
            f"{name}_1_2km": int(1 < d <= 2),
            f"{name}_2_3km": int(2 < d <= 3),
            f"{name}_3_5km": int(3 < d <= 5),
            f"{name}_5_10km": int(5 < d <= 10)
        }

    results = df.apply(encode_range, axis=1, result_type='expand')
    df = pd.concat([df, results], axis=1)

In [9]:
df

,price,land_area,address_line_2,latitude,longitude,price_per_m2,geometry,index_right,population,h_id,...,Phsar_Chas_1_2km,Phsar_Chas_2_3km,Phsar_Chas_3_5km,Phsar_Chas_5_10km,near_Phsar_kandal_in_km,Phsar_kandal_nearest,Phsar_kandal_1_2km,Phsar_kandal_2_3km,Phsar_kandal_3_5km,Phsar_kandal_5_10km
0,1100000.0,124.0,Chakto Mukh,11.575610,104.920250,8870.967742,POINT (104.92025 11.57561),53920.0,16252.0,8865846aadfffff,...,0,0,0,0,1,0,1,0,0,0
1,1100000.0,124.0,Chakto Mukh,11.575610,104.920250,8870.967742,POINT (104.92025 11.57561),53920.0,16252.0,8865846aadfffff,...,0,0,0,0,1,0,1,0,0,0
2,1100000.0,124.0,Chakto Mukh,11.575610,104.920250,8870.967742,POINT (104.92025 11.57561),53920.0,16252.0,8865846aadfffff,...,0,0,0,0,1,0,1,0,0,0
3,1100000.0,124.0,Chakto Mukh,11.575610,104.920250,8870.967742,POINT (104.92025 11.57561),53920.0,16252.0,8865846aadfffff,...,0,0,0,0,1,0,1,0,0,0
4,1100000.0,124.0,Chakto Mukh,11.575610,104.920250,8870.967742,POINT (104.92025 11.57561),53920.0,16252.0,8865846aadfffff,...,0,0,0,0,1,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7160,550000.0,550000.0,Boeng Reang,11.575837,104.920096,1.000000,POINT (104.920096 11.575837),53920.0,16252.0,8865846aadfffff,...,0,0,0,0,1,0,1,0,0,0
7161,550000.0,550000.0,Boeng Reang,11.575837,104.920096,1.000000,POINT (104.920096 11.575837),53920.0,16252.0,8865846aadfffff,...,0,0,0,0,1,0,1,0,0,0
7162,550000.0,550000.0,Boeng Reang,11.575837,104.920096,1.000000,POINT (104.920096 11.575837),53920.0,16252.0,8865846aadfffff,...,0,0,0,0,1,0,1,0,0,0
7163,550000.0,550000.0,Boeng Reang,11.575837,104.920096,1.000000,POINT (104.920096 11.575837),53920.0,16252.0,8865846aadfffff,...,0,0,0,0,1,0,1,0,0,0
7164,550000.0,550000.0,Boeng Reang,11.575837,104.920096,1.000000,POINT (104.920096 11.575837),53920.0,16252.0,8865846aadfffff,...,0,0,0,0,1,0,1,0,0,0

In [10]:
df.to_csv("../../../data/processed/realestate_clean_name_ppl.csv", index=False)